# Generated by Django 3.2.3 on 2021-05-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cube', '0002_alter_solvetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvetime',
            options={'get_latest_by': ['-priority', 'created']},
        ),
    ]
