# Generated by Django 3.2.3 on 2021-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cube', '0005_auto_20210604_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='classification',
            field=models.CharField(choices=[('OLL', 'OLL'), ('PLL', 'PLL')], max_length=25),
        ),
    ]
